### PR TITLE
Added CI support

### PR DESCRIPTION
**Pull request by LTLA**

### CODE REVIEW

**Comment by LTLA** [comment]
Why do we have so many tests for outdated R versions? Who cares?

**Comment by kevinrue** [comment]
Damn I thought I removed them. Must have forgotten to save the file or something.

**Comment by LTLA** [comment]
Note that I don't actually get admin privileges on other user's repositories. I can't force this through, for example.

**Comment by kevinrue** [comment]
Mmmh. I may have got too used to organisations. Doesn't seem like I can make you an admin. Correct me if I'm wrong

**Pull request merged**
